# Generated by Django 5.2.7 on 2025-12-23 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingsession',
            name='toss_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bettingsession',
            name='toss_winner',
            field=models.ForeignKey(blank=True, help_text='Player who won the toss and picks first', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_won_toss', to=settings.AUTH_USER_MODEL),
        ),
    ]
