# Generated by Django 6.0 on 2025-12-23 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bettingsession_toss_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='batting_average',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Batting average', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='picture',
            field=models.ImageField(blank=True, help_text='Player profile picture', null=True, upload_to='players/'),
        ),
        migrations.AddField(
            model_name='player',
            name='strike_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Strike rate', max_digits=5, null=True),
        ),
    ]
