# Generated by Django 6.0 on 2025-12-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_player_batting_average_player_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, help_text='Team logo/icon', null=True, upload_to='team_logos/'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External logo URL (fallback)', null=True),
        ),
    ]
