# Generated by Django 5.2.7 on 2025-12-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_team_logo_alter_team_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_in_playing_eleven',
            field=models.BooleanField(default=False, help_text='Whether this player is in the playing eleven for the current/upcoming match'),
        ),
    ]
