# Generated by Django 5.2.7 on 2025-12-24 22:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_player_is_in_playing_eleven'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='insurance_claimed',
            field=models.BooleanField(default=False, help_text='Whether insurance was claimed'),
        ),
        migrations.AddField(
            model_name='bet',
            name='insurance_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insurance percentage (0-20%) of bet amount', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='bet',
            name='insurance_premium',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Insurance premium paid (deducted upfront)', max_digits=10),
        ),
        migrations.AddField(
            model_name='bet',
            name='insurance_refunded',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount refunded from insurance', max_digits=10),
        ),
        migrations.AddField(
            model_name='bet',
            name='insured_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount insured (insurance_percentage × estimated_payout)', max_digits=10),
        ),
    ]
