# Generated by Django 6.0 on 2025-12-26 23:59

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bet_insurance_claimed_bet_insurance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bettingsession',
            name='fixed_bet_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Fixed bet amount for the entire session (combined bet)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
