# Generated by Django 6.0 on 2025-12-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bettingsession_fixed_bet_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(blank=True, help_text='Email of invitee if not a registered user', max_length=254, null=True)),
                ('invitee_username', models.CharField(blank=True, help_text='Username of invitee if registered', max_length=150, null=True)),
                ('invite_code', models.CharField(db_index=True, help_text='Unique code for invite link', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Optional message from inviter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invite expiration time (default 7 days)')),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invitee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='core.bettingsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['invite_code'], name='core_sessio_invite__9693f3_idx'), models.Index(fields=['status', 'expires_at'], name='core_sessio_status_a8533f_idx')],
            },
        ),
    ]
