# Generated by Django 6.0 on 2026-01-04 10:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_depositrequest_dltransaction_dlwallet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(help_text='Team name or session label', max_length=200)),
                ('bet_type', models.CharField(choices=[('back', 'Back'), ('lay', 'Lay'), ('not', 'Not'), ('yes', 'Yes')], max_length=10)),
                ('odds', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('1.01'))])),
                ('stake', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_bets', to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_bets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['match', 'selection', 'bet_type'], name='core_matchb_match_i_183a6a_idx'), models.Index(fields=['user', '-created_at'], name='core_matchb_user_id_9e5e48_idx')],
            },
        ),
        migrations.CreateModel(
            name='MatchBetBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(help_text='Team name or session label', max_length=200)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Running balance/profit for this selection', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_balances', to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['match', 'user'], name='core_matchb_match_i_b880cc_idx'), models.Index(fields=['match', 'selection'], name='core_matchb_match_i_e2d858_idx')],
                'unique_together': {('match', 'user', 'selection')},
            },
        ),
    ]
