# Generated by Django 6.0 on 2026-01-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_bet_type_to_matchbetbalance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='matchbetbalance',
            new_name='core_matchb_match_i_79b50a_idx',
            old_name='core_matchb_match_i_bet_typ_idx',
        ),
    ]
