# Generated by Django 5.2.7 on 2026-01-06 02:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_session_to_matchbetbalance_bet_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_settled',
            field=models.BooleanField(default=False, help_text='Whether all bets for this match have been settled'),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, help_text='Winning team (set when match is completed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_won', to='core.team'),
        ),
        migrations.CreateModel(
            name='MatchUserExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total stake amount exposed in this match', max_digits=12)),
                ('is_settled', models.BooleanField(default=False, help_text='Whether this exposure has been settled')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_exposures', to='core.match')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_exposures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['match', 'user'], name='core_matchu_match_i_5b7614_idx'), models.Index(fields=['user', '-updated_at'], name='core_matchu_user_id_b8cd2d_idx')],
                'unique_together': {('match', 'user')},
            },
        ),
    ]
