# Generated by Django 6.0 on 2025-12-27 08:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dl_code',
            field=models.CharField(blank=True, help_text='Unique code for DL user', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dl_user',
            field=models.ForeignKey(blank=True, help_text='DL User assigned to this end user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='master_dl',
            field=models.ForeignKey(blank=True, help_text='Master DL who created this DL user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dl_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('master_dl', 'Master DL'), ('dl', 'DL User'), ('end_user', 'End User')], default='end_user', help_text='Type of user in the distributor system', max_length=20),
        ),
    ]
