# Generated by Django 5.2.7 on 2025-12-27 11:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_dl_code_userprofile_dl_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='match_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage for matches', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_win_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Maximum win limit for this client', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_commission',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Commission percentage for sessions', max_digits=5, null=True),
        ),
    ]
