from django.urls import path
from . import views
from . import job_views

app_name = 'core'

urlpatterns = [
    path('', views.home, name='home'),
    path('match/<int:match_id>/', views.match_detail, name='match_detail'),
    path('match/<int:match_id>/create-session/', views.create_betting_session, name='create_betting_session'),
    path('session/<int:session_id>/', views.session_detail, name='session_detail'),
    path('session/<int:session_id>/join/', views.join_betting_session, name='join_betting_session'),
    path('session/<int:session_id>/toss/', views.perform_toss, name='perform_toss'),
    path('session/<int:session_id>/pick-player/', views.pick_player, name='pick_player'),
    path('session/<int:session_id>/check-updates/', views.check_session_updates, name='check_session_updates'),
    path('session/<int:session_id>/place-bet/', views.place_bet, name='place_bet'),
    path('session/<int:session_id>/settle/', views.settle_session, name='settle_session'),
    path('session/<int:session_id>/add-winnings/', views.add_winnings_to_wallet, name='add_winnings_to_wallet'),
    path('session/<int:session_id>/withdraw-winnings/', views.withdraw_winnings, name='withdraw_winnings'),
    path('wallet/', views.wallet_view, name='wallet'),
    path('wallet/deposit/', views.deposit_wallet, name='deposit_wallet'),
    path('account-statement/', views.account_statement, name='account_statement'),
    path('profit-loss/', views.profit_loss, name='profit_loss'),
    path('bet-history/', views.bet_history, name='bet_history'),
    path('change-password/', views.change_password, name='change_password'),
    path('reports/', views.end_user_reports, name='end_user_reports'),
    # Invite endpoints
    path('session/<int:session_id>/invite/', views.send_invite, name='send_invite'),
    path('session/<int:session_id>/invite/<str:invite_code>/', views.accept_invite, name='accept_invite'),
    path('invites/', views.my_invites, name='my_invites'),
    path('invite/<int:invite_id>/decline/', views.decline_invite, name='decline_invite'),
    path('api/search-users/', views.search_users, name='search_users'),
    path('api/wallet-info/<str:info_type>/', views.wallet_info_api, name='wallet_info_api'),
    # Job endpoint (to prevent 404 errors from polling)
    path('job/check_for_completed_jobs/', job_views.check_for_completed_jobs, name='check_for_completed_jobs'),
    # Distributor/Dealer System URLs
    path('master-dl/', views.master_dl_dashboard, name='master_dl_dashboard'),
    path('master-dl/create-dl/', views.create_dl_user, name='create_dl_user'),
    path('master-dl/credit/<int:dl_user_id>/', views.credit_dl_wallet, name='credit_dl_wallet'),
    path('master-dl/withdraw/<int:dl_user_id>/', views.withdraw_dl_wallet, name='withdraw_dl_wallet'),
    path('master-dl/reset-password/<int:dl_user_id>/', views.reset_dl_password, name='reset_dl_password'),
    path('master-dl/add-points/<int:dl_user_id>/', views.master_dl_add_points, name='master_dl_add_points'),
    path('master-dl/subtract-points/<int:dl_user_id>/', views.master_dl_subtract_points, name='master_dl_subtract_points'),
    path('master-dl/statement/', views.master_dl_statement, name='master_dl_statement'),
    path('master-dl/user/<int:dl_user_id>/statement/', views.master_dl_user_statement, name='master_dl_user_statement'),
    path('master-dl/reports/', views.master_dl_reports, name='master_dl_reports'),
    path('dl/home/', views.dl_home, name='dl_home'),
    path('dl/dashboard/', views.dl_dashboard, name='dl_dashboard'),
    path('dl/add-user/', views.dl_add_user, name='dl_add_user'),
    path('dl/edit-user/<int:end_user_id>/', views.dl_edit_user, name='dl_edit_user'),
    path('dl/match-book/', views.dl_match_book, name='dl_match_book'),
    path('dl/reports/', views.dl_reports, name='dl_reports'),
    path('dl/approve-deposit/<int:request_id>/', views.approve_deposit_request, name='approve_deposit'),
    path('dl/reject-deposit/<int:request_id>/', views.reject_deposit_request, name='reject_deposit'),
    path('dl/credit-end-user/<int:end_user_id>/', views.dl_credit_end_user, name='dl_credit_end_user'),
    path('dl/withdraw-end-user/<int:end_user_id>/', views.dl_withdraw_end_user, name='dl_withdraw_end_user'),
    path('dl/user/<int:end_user_id>/statement/', views.dl_user_statement, name='dl_user_statement'),
    path('dl/assign-end-user/', views.dl_assign_end_user, name='dl_assign_end_user'),
    path('dl/transactions/', views.dl_transactions, name='dl_transactions'),
    path('request-deposit/', views.request_deposit, name='request_deposit'),
    path('my-deposit-requests/', views.my_deposit_requests, name='my_deposit_requests'),
]
